# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_markup}
  s.version = "1.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Landau"]
  s.date = %q{2010-09-04}
  s.description = %q{Represent ActiveRecord Markdown, Textile, Wiki text, RDoc columns as Markdown, Textile Wikitext, RDoc objects using various external libraries to convert to HTML.}
  s.email = %q{brian.landau@viget.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "acts_as_markup.gemspec",
     "lib/acts/as_markup.rb",
     "lib/acts_as_markup.rb",
     "lib/acts_as_markup/exts/maruku.rb",
     "lib/acts_as_markup/exts/object.rb",
     "lib/acts_as_markup/exts/peg_markdown.rb",
     "lib/acts_as_markup/exts/rdiscount.rb",
     "lib/acts_as_markup/exts/rdoc.rb",
     "lib/acts_as_markup/exts/wikitext.rb",
     "lib/acts_as_markup/stringlike.rb",
     "tasks/rdoc.rb",
     "tasks/test.rb",
     "test/acts_as_markdown_test.rb",
     "test/acts_as_markup_test.rb",
     "test/acts_as_rdoc_test.rb",
     "test/acts_as_textile_test.rb",
     "test/acts_as_wikitext_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://vigetlabs.github.com/acts_as_markup/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Represent ActiveRecord Markdown, Textile, Wiki text, RDoc columns as Markdown, Textile Wikitext, RDoc objects using various external libraries to convert to HTML.}
  s.test_files = [
    "test/acts_as_markdown_test.rb",
     "test/acts_as_markup_test.rb",
     "test/acts_as_rdoc_test.rb",
     "test/acts_as_textile_test.rb",
     "test/acts_as_wikitext_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<rdiscount>, ["~> 1.3"])
      s.add_runtime_dependency(%q<wikitext>, ["~> 2.0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<activerecord>, [">= 2.3.2"])
      s.add_dependency(%q<rdiscount>, ["~> 1.3"])
      s.add_dependency(%q<wikitext>, ["~> 2.0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<activerecord>, [">= 2.3.2"])
    s.add_dependency(%q<rdiscount>, ["~> 1.3"])
    s.add_dependency(%q<wikitext>, ["~> 2.0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2"])
  end
end

